language: cpp
matrix:
  include:
    - os: linux
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
    - os: linux
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
before_install:
  - eval "${MATRIX_EVAL}"
script: $CXX -std=c++14 test.cpp && ./a.out
